export const colors = {
  canvas: "var(--canvas)",
  surface: "var(--surface)",
  surfaceElevated: "var(--surface-elevated)",
  surfaceSubtle: "var(--surface-subtle)",
  surfaceMuted: "var(--surface-muted)",
  ink: "var(--ink)",
  inkSecondary: "var(--ink-secondary)",
  muted: "var(--muted)",
  faint: "var(--faint)",
  line: "var(--line)",
  lineLight: "var(--line-light)",
  gold: "var(--accent)",
  goldHover: "var(--accent-hover)",
  goldSoft: "var(--accent-soft)",
  goldMuted: "var(--accent-muted)",
  goldBorder: "var(--accent-border)",
  goldDark: "var(--accent-ink)",
  darkCard: "var(--dark-card)",
  darkCardSurface: "var(--dark-card-surface)",
  mint: "var(--success-soft)",
  mintInk: "var(--success)",
  blue: "var(--info-soft)",
  blueInk: "var(--info)",
  lilac: "var(--neutral-soft)",
  lilacInk: "var(--muted)",
  coral: "var(--danger-soft)",
  coralInk: "var(--danger)",
  danger: "var(--danger)",
  success: "var(--success)",
  overlay: "var(--overlay)",
} as const;

export const radii = {
  xs: 8,
  small: 12,
  medium: 18,
  large: 24,
  xl: 32,
  pill: 999,
} as const;

export const shadows = {
  subtle: "var(--shadow-subtle)",
  card: "var(--shadow-card)",
  goldGlow: "var(--shadow-accent)",
  floating: "var(--shadow-floating)",
} as const;
